CREATE DATABASE IF NOT EXISTS MJU_CORONA_DIAGNOSIS_MACRO;

USE MJU_CORONA_DIAGNOSIS_MACRO;

CREATE TABLE IF NOT EXISTS UserInfo (
    stud_id INTEGER NOT NULL,
    pw VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    last_classdate DATE NOT NULL,
    CONSTRAINT USER_INFO_PK PRIMARY KEY (stud_id)
);